[forest]
trees = ["trees" ]                   # The directories in which your trees are stored.css
assets = ["assets"]                  # The directories in which your assets are stored
url = "https://cahilfil.xyz/"
